### ISSUE TITLE
Crash after picking an image from gallery

### ISSUE THREAD

**Issue by Imikeeee** [mollyim/mollyim-android#42] opened 2021-04-29 19:36 UTC
Updated from the F-Droid , ofc the camera not working at all (i opened an issue before) and when i want to pick an image from the gallery the app is lock itself (password screen) but the wiping is not showing up so yea I think its a big problem.

**Comment by valldrac** [comment] 2021-04-29 22:21
When the app crashes, the lock is activated but the wipe process is not run. So Molly is crashing in your case.

Can you please submit the debug log and post the link here? You can also email the link to support@molly.im

Here you have the instructions to submit the debug log: https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

**Comment by Imikeeee** [comment] 2021-04-30 20:35
I sent you an email with P40PRO subject

**Comment by valldrac** [comment] 2021-05-01 20:46
Thanks for the email. I reviewed the debug log and it is related to this bug: https://github.com/signalapp/Signal-Android/issues/10624

The root cause seems to be a buggy library used for reading media files, present in some Huawei devices. And the trigger in your case is a file stored in your gallery that crashes Molly (or Signal doesn't matter) when it tries to render the thumbnail to display it in the gallery.

First, I would recommend updating your phone's Android version. If not, try to identify the file that is crashing the app and remove it from the gallery. 

There's not much else i can do. I don't have any Huawei device for testing. Eventually the Signal team will fix it in Signal, and so also in Molly.

**Comment by Chromatros** [comment] 2022-06-06 22:35
This can be closed

**Comment by valldrac** [comment] 2022-06-11 00:01
OK, closing it now. But if it is not fixed yet, please let me know.

**Closed by valldrac** 2022-06-11 00:01 UTC
Labels: bug, upstream
