### ISSUE TITLE
Google Play services error after switch to Molly

### ISSUE THREAD

**Issue by pio2398** [mollyim/mollyim-android#54] opened 2021-06-18 17:37 UTC
I installed Molly from f-droid, after start message about missing Google Play services appeared.
Signal works before without any problem. Other apps also seem to be working.   

Interesting part from logcat:
```
GooglePlayServicesUtil: Google Play Store is missing.
JobRunner: [JOB::e407e29d-f8ca-44ec-b89e-7aa3b3647091][FcmRefreshJob][3] Job finished with result SUCCESS in 11 ms. (Time Since Submission: 81 ms, Lifespan: 300000 ms, Run Attempt: 1/
ConversationListDataSou: [size(), UnarchivedConversationListDataSource] 7 ms
im.molly.app: Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
im.molly.app: Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
im.molly.app: Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
LoggingFragment: [ConversationListFragmen] onStart()
ApplicationContext: App is now visible.
FrameRateTracker: Beginning frame rate tracking. Screen refresh rate: 60.00 hz, or 16.67 ms per frame.
ApplicationContext: onStart() took 0 ms
```

**Comment by valldrac** [comment] 2021-06-18 17:53
What version of Molly did you installed? Molly or Molly-FOSS? Both are available in f-droid, but in different repositories. Check https://molly.im/fdroid/

If your device doesn't have the official Play Services, better to use Molly-FOSS.

You can install Signal again and see if you get the same error. Molly and Signal share the same code regarding Google Play Services. Only Molly-FOSS is different.

**Comment by piotr-szegda** [comment] 2021-06-18 18:04
Molly version. I tried to install it again from f-droid and apk from website end result is similar.
I have rooted device with custom rom but gapps seem to work in other apps and Signal.

**Comment by valldrac** [comment] 2021-06-18 18:18
Can you please try the previous version? This one https://github.com/mollyim/mollyim-android/releases/download/v5.10.8-1/Molly-production-v5.10.8-1.apk

Just you to know, the APK files from GitHub and f-droid are the same.

**Comment by piotr-szegda** [comment] 2021-06-18 18:24
Some problem.

**Comment by valldrac** [comment] 2021-06-18 18:29
Thanks. Signal and Molly should have the same behaviour.

Can you please tell me exactly the message you get in Molly? There are many errors related to Play Services.

When happens? At registration? Or later in the conversation list?

**Comment by piotr-szegda** [comment] 2021-06-18 18:39
Firstly I got that message after entering phone number.

![Screenshot_20210618-203217](https://user-images.githubusercontent.com/977500/122603787-3098bf80-d075-11eb-9439-3d7544eeac5c.jpg)

After registration I also have similar message in the conversation list.

**Comment by piotr-szegda** [comment] 2021-06-18 18:44
Next error:
![Screenshot_20210618-204221](https://user-images.githubusercontent.com/977500/122604293-04317300-d076-11eb-8391-9546904fa866.png)

**Comment by valldrac** [comment] 2021-06-18 18:46
Okay, one last question. What package do you use for Play Services in your custom ROM? Official GApps? microG? OpenGApps?

**Comment by piotr-szegda** [comment] 2021-06-18 18:55
Integrated in ROM, hard to say exactly. I am using this ROM: https://forum.xda-developers.com/t/01-06-viperexperience-beta-5-android-11-may-2021-security-patch-gsi.4063321/

**Comment by valldrac** [comment] 2021-06-19 19:37
The ROM includes the Play Services from Google. I verified it.

It seems that by default, Google doesn't allow apps to use Play Services in "insecure" devices (e.g. with custom ROMs). The developer of the app can change that in the Play Store console and allow it, as Signal probably did. But Molly is not distributed in Play Store, so I cannot change it.

Until Molly is distributed in the Play Store, push notifications via Play Services will not work with custom ROMs. As a workaround, you can accept the error message and the app will use websocket notifications. It's supposed to have higher energy consumption, but many users have reported that the actual impact on the battery is negligibly.

**Comment by piotr-szegda** [comment] 2021-06-19 20:21
Device status is certified in Google Play, safetynet is passing. I even tried to enable Magisk Hide for Molly but still it's not working.

**Comment by valldrac** [comment] 2021-06-19 23:14
If Google Play does not complaining it should work.

Could you please share the debuglog and send the link to support@molly.im? Right after passing the registration step, when the application shows the error in the conversation list. To submit the log, go to Settings> Help> Debug Log

**Comment by valldrac** [comment] 2021-06-20 16:42
Thanks for the logs.

Molly is receiving SERVICE_INVALID (error code 9) from the Play Services library. This is related to the message you already pointed out:

```
06-20 11:57:33.575  8109  8154 W GooglePlayServicesUtil: Google Play Store is missing.
```

I quickly disassembled the library and confirmed it. Basically, it searches for the Play Store app and fails with this error if it is not installed in the device.

I don't understand how it can work with Signal. Did you install Signal from their site? https://signal.org/android/apk/

Alternatively, you can install the Play Store app and try again.

**Comment by valldrac** [comment] 2021-07-05 23:10
I close this issue because without additional information this doesn't appear to be a bug in Molly.

**Closed by valldrac** 2021-07-05 23:10 UTC

**Comment by hardhub** [comment] 2023-08-29 17:26
> Thanks for the logs.
> 
> Molly is receiving SERVICE_INVALID (error code 9) from the Play Services library. This is related to the message you already pointed out:
> 
> ```
> 06-20 11:57:33.575  8109  8154 W GooglePlayServicesUtil: Google Play Store is missing.
> ```
> 
> I quickly disassembled the library and confirmed it. Basically, it searches for the Play Store app and fails with this error if it is not installed in the device.
> 
> I don't understand how it can work with Signal. Did you install Signal from their site? https://signal.org/android/apk/
> 
> Alternatively, you can install the Play Store app and try again.

@valldrac I have the same issue with Lineage and GApps Pico version

I have removed mostly all except play services themselves, dialer package, installer package, and battery usage.

Include
# Pico+
# CalSync                 # Install Google Calendar Sync (if Google Calendar is being installed)
# GoogleTTS               # Install Google Text-to-Speech Engine (Micro+ on 5.0-, Pico+ on 6.0+)
DialerFramework         # Install Dialer Framework (Android 6.0+)
PackageInstallerGoogle  # Install Package Installer (Android 6.0 only & Android 8.0+)
# GearheadStub            # Install Android Auto stub. Android Auto needs to be updated to function. Android 10+.

# Nano+
BatteryUsage            # Install Device Health Services (Android 7.1+)

**Comment by wokawoka** [comment] 2023-09-26 18:10
I am experiencing the same problem.
Signal works through play services without any problem but molly is complaining about missing play services.
On an old motorola stock android 8 os (rooted)

**Comment by maximko** [comment] 2023-11-24 20:01
Same for me using Lineage OS 20 nightly (Android 13) and the latest MindTheGapps. I've installed Molly-v6.40.4-1.apk. I also have magisk and lsposed on my phone.

**Comment by DXCanas** [comment] 2024-04-14 09:35
Same deal here. Stock ROM on a Samsung tablet as a client, no root.

**Comment by valldrac** [comment] 2024-04-14 22:06
@DXCanas This issue has been closed for months. Please, start a new issue and fill out the bug report.

**Comment by wokawoka** [comment] 2024-04-15 07:20
> @DXCanas This issue has been closed for months. Please, start a new issue and fill out the bug report.

Wouldn't it be more accurate to reopen this issue, since the problem hasn't been resolved?
I am experiencing the same issue on both my two devices.
