### ISSUE TITLE
Video navigation buttons don't disappear

### ISSUE THREAD

**Issue by flippflapp** [mollyim/mollyim-android#130] opened 2022-09-26 16:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When someone sends me a video and I play it in the chat, all navigation buttons (i.e. play/pause/download/forward/...) don't go away, neither after tapping the display again or after waiting. This happens in landscape and portrait orientation. This has been reproduced bu nutts0 on another device.

### Steps to reproduce

1. Play a video within a chat.

### Molly version

v5.48.3-1-FOSS

### Android version

Android 13, GrapheneOS TP1A.220905.004.2022092300

### Device

Google Pixel4a

**Comment by valldrac** [comment] 2022-09-27 16:30
Thanks for the issue report. We cannot reproduce it anymore after merging 5.50.4. Seems this bug was fixed by Signal.

**Closed by valldrac** 2022-09-27 16:30 UTC
Labels: bug, upstream
