### ISSUE TITLE
Molly Crashes

### ISSUE THREAD

**Issue by Graph3n** [mollyim/mollyim-android#117] opened 2022-08-12 16:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello Molly just crashed in chat when I was writing now it do not open it show just logo and you cannot enter it.

Is there a way to fix this I need my contacts etc.
Or if someone can make me a version that will recognise it as update so it overruns itself so I can enter.

I really need my contacts please help anyone is the best app ever not sure why this happen on latest version suddenly and it worked fine

### Steps to reproduce

1.App crashed
2.Maybe do a same version of app that update itself so I can make it functional

### Molly version

v5.44.3-1

### Android version

android 12

### Device

Google pixel 6

### Link to debug log

do not have

**Comment by tuxiqae** [comment] 2022-08-14 07:37
Duplicate of #116?

**Closed** 2022-08-16 17:49 UTC
Labels: duplicate
