### ISSUE TITLE
App Crashing After Registration

### ISSUE THREAD

**Issue by Jatinverma0786** [mollyim/mollyim-android#60] opened 2021-07-15 11:02 UTC
App Getting Crashed in Android below version 10 After Registration This is Critical Issue.

**Comment by valldrac** [comment] 2021-07-15 12:14
I cannot reproduce your issue. I tested Android 5 and Android 7.1

Can you please submit the debug log and post the link here? You can also email the link to support@molly.im

The instructions to submit the debug log are here https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports. Maybe you would need to capture the log after the crash with `adb logcat`

**Comment by Jatinverma0786** [comment] 2021-07-15 15:36
how to debug log because the application is crashing as soon as it is opened

**Comment by valldrac** [comment] 2021-07-19 11:28
What version of the app did you use?

**Comment by valldrac** [comment] 2021-08-02 10:50
I think this is already fixed in v5.16.3-2. I was unable to reproduce it because at the time the issue was open, the bug was only present in master and it had not yet shipped in any release.

If this is the case, @Jatinverma0786 is probably using a Molly fork.

**Closed by valldrac** 2021-08-02 10:50 UTC
Labels: bug
