### ISSUE TITLE
Molly Crashes on attempted opening of a group chat

### ISSUE THREAD

**Issue by Lantern47** [mollyim/mollyim-android#41] opened 2021-04-29 16:59 UTC
I am in a group chat with 4 other signal users. Whenever I try to open this chat to read its contents, Molly crashes instantly, yet if there is a notification for a new message in said group chat, I may access the chat without issue only as long as I select the notification. 
Attempting to open the chat manually by selecting it within Molly crashes the app.

I am in two group chats currently, the one that causes the crashes only holds 5 users including myself. The other chat holds 20+ and causes me no issue.

I downloaded and installed Molly from the F-DROID repository and am running Android version 7.0 but my phone informs me whenever I check for new updates that it's software is up to date. 

Edit: in attempt to send in the debug log, it notified me that it is, without specifying why, unable to submit the debug log.

**Comment by valldrac** [comment] 2021-04-29 18:12
Sorry for that. I would need the debug log to find the cause.

Please read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports, specially the section "How to capture a debug log". Then share the link to the debug log here or email it to support@molly.im

**Comment by Lantern47** [comment] 2021-04-29 21:58
> Sorry for that. I would need the debug log to find the cause.
> 
> Please read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports, specially the section "How to capture a debug log". Then share the link to the debug log here or email it to [support@molly.im](mailto:support@molly.im)

Every time I try to submit the debug log it says it can't submit it. I have a working internet connection. I can't copy the text of the debug log either, it only lets me delete lines.

**Comment by valldrac** [comment] 2021-04-29 22:17
There was a bug in the previous version with the debug log submission. It's already fixed in the latest version. Could it be that you are running an older version?

Check in Settings > Advanced what version are you running. The latest is v5.8.10-1.

Download the APK from here: https://github.com/mollyim/mollyim-android/releases/tag/v5.8.10-1. Or enable the auto-updater also in Settings > Advanced.

**Comment by valldrac** [comment] 2021-06-15 09:12
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

**Closed by valldrac** 2021-06-15 09:12 UTC
Labels: bug
