### ISSUE TITLE
Import failure

### ISSUE THREAD

**Issue by pabloscloud** [mollyim/mollyim-android#191] opened 2023-05-14 17:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am trying to import my backup but get the following error:

"Backup contains malformed data"

### Steps to reproduce

Create a backup using the latests version (v6.19.9-1) and restore using the latest version (v6.19.9-1).

### Molly version

v6.19.9-1 foss

### Device

Google Pixel 4a (5g)

**Comment by wreps8Owt** [comment] 2023-06-11 17:28
This issue remains in v6.20.5-1-FOSS.

I can only get some information via adb logcat:

> 06-12 01:10:11.554  5964  6043 I RestoreBackupFragment: Starting backup restore.
06-12 01:10:11.554  1709  2612 D CoreBackPreview: Window{5735938 u0 im.molly.app/org.thoughtcrime.securesms.registration.RegistrationNavigationActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@dbec22d, mPriority=0}
06-12 01:10:11.555  1709  3017 D CoreBackPreview: Window{5735938 u0 im.molly.app/org.thoughtcrime.securesms.registration.RegistrationNavigationActivity}: Setting back callback null
06-12 01:10:11.556  5964  5997 D OpenGLRenderer: endAllActiveAnimators on 0xb400d0ebde05da00 (RippleDrawable) with handle 0xb400cfcec9313f00
06-12 01:10:11.557  1709  2612 W InputManager-JNI: Input channel object '5735938 im.molly.app/org.thoughtcrime.securesms.registration.RegistrationNavigationActivity (client)' was disposed without first being removed with the input manager!
06-12 01:10:11.610  3434  3667 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Molly/Backups/molly-2023-06-11-23-45-53.backup. Uid: 10028. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
06-12 01:10:11.612  1709  2000 V WindowManager: Unknown focus tokens, dropping reportFocusChanged
06-12 01:10:12.065  5964  6043 I FullBackupImporter: Dropping trigger: message_ai
06-12 01:10:12.066  5964  6043 I FullBackupImporter: Dropping trigger: message_ad
06-12 01:10:12.066  5964  6043 I FullBackupImporter: Dropping trigger: message_au
06-12 01:10:12.066  5964  6043 I FullBackupImporter: Dropping trigger: msl_message_delete
06-12 01:10:12.066  5964  6043 I FullBackupImporter: Dropping trigger: msl_attachment_delete
06-12 01:10:12.072  5964  6043 I FullBackupImporter: Tables that depend on avatar_picker: []
06-12 01:10:12.072  5964  6043 I FullBackupImporter: Tables that depend on call: []
06-12 01:10:12.072  5964  6043 I FullBackupImporter: Tables that depend on call_link: [call]
06-12 01:10:12.072  5964  6043 I FullBackupImporter: Tables that depend on cds: []
06-12 01:10:12.072  5964  6043 I FullBackupImporter: Tables that depend on chat_colors: []
06-12 01:10:12.072  5964  6043 I FullBackupImporter: Tables that depend on distribution_list: [distribution_list_member, story_sends]
06-12 01:10:12.072  5964  6043 I FullBackupImporter: Tables that depend on distribution_list_member: []
06-12 01:10:12.072  5964  6043 I FullBackupImporter: Tables that depend on donation_receipt: []
06-12 01:10:12.072  5964  6043 I FullBackupImporter: Tables that depend on drafts: []
06-12 01:10:12.073  5964  6043 I FullBackupImporter: Tables that depend on emoji_search: []
06-12 01:10:12.073  5964  6043 I FullBackupImporter: Tables that depend on group_membership: []
06-12 01:10:12.073  5964  6043 I FullBackupImporter: Tables that depend on group_receipts: []
06-12 01:10:12.073  5964  6043 I FullBackupImporter: Tables that depend on groups: []
06-12 01:10:12.073  5964  6043 I FullBackupImporter: Tables that depend on identities: []
06-12 01:10:12.073  5964  6043 I FullBackupImporter: Tables that depend on mention: []
06-12 01:10:12.073  5964  6043 I FullBackupImporter: Tables that depend on message: [call, reaction, story_sends]
06-12 01:10:12.073  5964  6043 I FullBackupImporter: Tables that depend on message_fts: []
06-12 01:10:12.073  5964  6043 I FullBackupImporter: Tables that depend on message_fts_config: []
06-12 01:10:12.073  5964  6043 I FullBackupImporter: Tables that depend on message_fts_data: []
06-12 01:10:12.073  5964  6043 I FullBackupImporter: Tables that depend on message_fts_docsize: []
06-12 01:10:12.074  5964  6043 I FullBackupImporter: Tables that depend on message_fts_idx: []
06-12 01:10:12.074  5964  6043 I FullBackupImporter: Tables that depend on msl_message: []
06-12 01:10:12.074  5964  6043 I FullBackupImporter: Tables that depend on msl_payload: [msl_recipient, msl_message]
06-12 01:10:12.074  5964  6043 I FullBackupImporter: Tables that depend on msl_recipient: []
06-12 01:10:12.074  5964  6043 I FullBackupImporter: Tables that depend on notification_profile: [notification_profile_allowed_members, notification_profile_schedule]
06-12 01:10:12.074  5964  6043 I FullBackupImporter: Tables that depend on notification_profile_allowed_members: []
06-12 01:10:12.074  5964  6043 I FullBackupImporter: Tables that depend on notification_profile_schedule: []
06-12 01:10:12.074  5964  6043 I FullBackupImporter: Tables that depend on one_time_prekeys: []
06-12 01:10:12.074  5964  6043 I FullBackupImporter: Tables that depend on part: []
06-12 01:10:12.074  5964  6043 I FullBackupImporter: Tables that depend on payments: []
06-12 01:10:12.075  5964  6043 I FullBackupImporter: Tables that depend on pending_pni_signature_message: []
06-12 01:10:12.075  5964  6043 I FullBackupImporter: Tables that depend on pending_retry_receipts: []
06-12 01:10:12.075  5964  6043 I FullBackupImporter: Tables that depend on push: []
06-12 01:10:12.075  5964  6043 I FullBackupImporter: Tables that depend on reaction: []
06-12 01:10:12.075  5964  6043 I FullBackupImporter: Tables that depend on recipient: [call, distribution_list_member, reaction, story_sends, pending_pni_signature_message, thread, distribution_list, message]
06-12 01:10:12.076  5964  6043 I FullBackupImporter: Tables that depend on remapped_recipients: []
06-12 01:10:12.076  5964  6043 I FullBackupImporter: Tables that depend on remapped_threads: []
06-12 01:10:12.076  5964  6043 I FullBackupImporter: Tables that depend on remote_megaphone: []
06-12 01:10:12.076  5964  6043 I FullBackupImporter: Tables that depend on sender_key_shared: []
06-12 01:10:12.076  5964  6043 I FullBackupImporter: Tables that depend on sender_keys: []
06-12 01:10:12.076  5964  6043 I FullBackupImporter: Tables that depend on sessions: []
06-12 01:10:12.076  5964  6043 I FullBackupImporter: Tables that depend on signed_prekeys: []
06-12 01:10:12.076  5964  6043 I FullBackupImporter: Tables that depend on sticker: []
06-12 01:10:12.076  5964  6043 I FullBackupImporter: Tables that depend on storage_key: []
06-12 01:10:12.076  5964  6043 I FullBackupImporter: Tables that depend on story_sends: []
06-12 01:10:12.076  5964  6043 I FullBackupImporter: Tables that depend on thread: [message]
06-12 01:10:12.077  5964  6043 I FullBackupImporter: Dropping table: avatar_picker
06-12 01:10:12.077  5964  6043 I FullBackupImporter: Dropping table: call
06-12 01:10:12.078  5964  6043 I FullBackupImporter: Dropping table: cds
06-12 01:10:12.078  5964  6043 I FullBackupImporter: Dropping table: chat_colors
06-12 01:10:12.079  5964  6043 I FullBackupImporter: Dropping table: distribution_list_member
06-12 01:10:12.079  5964  6043 I FullBackupImporter: Dropping table: donation_receipt
06-12 01:10:12.080  5964  6043 I FullBackupImporter: Dropping table: drafts
06-12 01:10:12.080  5964  6043 I FullBackupImporter: Dropping table: emoji_search
06-12 01:10:12.080  5964  6043 I FullBackupImporter: Dropping table: group_membership
06-12 01:10:12.081  5964  6043 I FullBackupImporter: Dropping table: group_receipts
06-12 01:10:12.081  5964  6043 I FullBackupImporter: Dropping table: groups
06-12 01:10:12.081  5964  6043 I FullBackupImporter: Dropping table: identities
06-12 01:10:12.082  5964  6043 I FullBackupImporter: Dropping table: mention
06-12 01:10:12.083  5964  6043 I FullBackupImporter: Dropping table: message_fts
06-12 01:10:12.084  5964  6043 I FullBackupImporter: Dropping table: message_fts_config
06-12 01:10:12.084  5964  6043 I FullBackupImporter: Dropping table: message_fts_data
06-12 01:10:12.084  5964  6043 I FullBackupImporter: Dropping table: message_fts_docsize
06-12 01:10:12.084  5964  6043 I FullBackupImporter: Dropping table: message_fts_idx
06-12 01:10:12.084  5964  6043 I FullBackupImporter: Dropping table: msl_message
06-12 01:10:12.085  5964  6043 I FullBackupImporter: Dropping table: msl_recipient
06-12 01:10:12.085  5964  6043 I FullBackupImporter: Dropping table: notification_profile_allowed_members
06-12 01:10:12.085  5964  6043 I FullBackupImporter: Dropping table: notification_profile_schedule
06-12 01:10:12.086  5964  6043 I FullBackupImporter: Dropping table: one_time_prekeys
06-12 01:10:12.087  5964  6043 I FullBackupImporter: Dropping table: part
06-12 01:10:12.087  5964  6043 I FullBackupImporter: Dropping table: payments
06-12 01:10:12.088  5964  6043 I FullBackupImporter: Dropping table: pending_pni_signature_message
06-12 01:10:12.088  5964  6043 I FullBackupImporter: Dropping table: pending_retry_receipts
06-12 01:10:12.089  5964  6043 I FullBackupImporter: Dropping table: push
06-12 01:10:12.089  5964  6043 I FullBackupImporter: Dropping table: reaction
06-12 01:10:12.089  5964  6043 I FullBackupImporter: Dropping table: remapped_recipients
06-12 01:10:12.090  5964  6043 I FullBackupImporter: Dropping table: remapped_threads
06-12 01:10:12.090  5964  6043 I FullBackupImporter: Dropping table: remote_megaphone
06-12 01:10:12.090  5964  6043 I FullBackupImporter: Dropping table: sender_key_shared
06-12 01:10:12.091  5964  6043 I FullBackupImporter: Dropping table: sender_keys
06-12 01:10:12.091  5964  6043 I FullBackupImporter: Dropping table: sessions
06-12 01:10:12.091  5964  6043 I FullBackupImporter: Dropping table: signed_prekeys
06-12 01:10:12.092  5964  6043 I FullBackupImporter: Dropping table: sticker
06-12 01:10:12.092  5964  6043 I FullBackupImporter: Dropping table: storage_key
06-12 01:10:12.093  5964  6043 I FullBackupImporter: Dropping table: story_sends
06-12 01:10:12.093  5964  6043 I FullBackupImporter: Dropping table: call_link
06-12 01:10:12.093  5964  6043 I FullBackupImporter: Dropping table: msl_payload
06-12 01:10:12.094  5964  6043 I FullBackupImporter: Dropping table: notification_profile
06-12 01:10:12.094  5964  6043 I FullBackupImporter: Dropping table: distribution_list
06-12 01:10:12.095  5964  6043 I FullBackupImporter: Dropping table: message
06-12 01:10:12.096  5964  6043 I FullBackupImporter: Dropping table: thread
06-12 01:10:12.096  5964  6043 I FullBackupImporter: Dropping table: recipient
0
06-12 01:10:15.027  5964  6043 W FullBackupImporter: Foreign key constraints failed!
06-12 01:10:15.027  5964  6043 W FullBackupImporter: ForeignKeyViolation(table=call, violatingRowId=23, dependsOnTable=message, column=message_id)
06-12 01:10:15.027  5964  6043 W FullBackupImporter: ForeignKeyViolation(table=call, violatingRowId=24, dependsOnTable=message, column=message_id)
06-12 01:10:15.027  5964  6043 W FullBackupImporter: ForeignKeyViolation(table=call, violatingRowId=25, dependsOnTable=message, column=message_id)
06-12 01:10:15.027  5964  6043 W FullBackupImporter: ForeignKeyViolation(table=call, violatingRowId=26, dependsOnTable=message, column=message_id)
06-12 01:10:15.027  5964  6043 W FullBackupImporter: ForeignKeyViolation(table=call, violatingRowId=27, dependsOnTable=message, column=message_id)
06-12 01:10:15.027  5964  6043 W FullBackupImporter: ForeignKeyViolation(table=call, violatingRowId=28, dependsOnTable=message, column=message_id)
06-12 01:10:15.027  5964  6043 W FullBackupImporter: ForeignKeyViolation(table=call, violatingRowId=29, dependsOnTable=message, column=message_id)
06-12 01:10:15.027  5964  6043 W FullBackupImporter: ForeignKeyViolation(table=call, violatingRowId=30, dependsOnTable=message, column=message_id)
06-12 01:10:15.027  5964  6043 W FullBackupImporter: ForeignKeyViolation(table=call, violatingRowId=31, dependsOnTable=message, column=message_id)
06-12 01:10:15.027  5964  6043 W FullBackupImporter: ForeignKeyViolation(table=call, violatingRowId=32, dependsOnTable=message, column=message_id)
06-12 01:10:15.027  5964  6043 W FullBackupImporter: ForeignKeyViolation(table=call, violatingRowId=33, dependsOnTable=message, column=message_id)
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: Failed due to foreign key constraint violations.
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: org.thoughtcrime.securesms.backup.FullBackupImporter$ForeignKeyViolationException: call -> message_id
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:122)
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:75)
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:288)
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
06-12 01:10:15.029  5964  6043 W RestoreBackupFragment: 	at java.lang.Thread.run(Thread.java:1012)

**Comment by wreps8Owt** [comment] 2023-06-11 17:29
This issue affects account "transfer from android device" as well.

**Comment by dreamflasher** [comment] 2023-07-07 13:27
I can confirm that this bug continues to exist in 6.24.4-1. All backups from Molly are broken. Investigating with signalbackup-tools shows the error of "WARNING Foreign key constraint violated" which has been observed by others: https://github.com/bepaald/signalbackup-tools/issues/118

**Comment by valldrac** [comment] 2023-07-08 18:02
Are the backups old? What version of Molly or Signal were they created with?

**Comment by dreamflasher** [comment] 2023-07-09 09:08
Molly 6.24.4-1 was used to create the backup, and Molly 6.24.4-1 was tried for restoring the backup. Signal was not used. The backup was 3 days old.

**Comment by pabloscloud** [comment] 2023-07-15 11:34
I just tried it again and I still face the same issue. I tried exporting from molly and importing into Signal

Molly Version: v6.25.5-1-FOSS
Signal Version: 6.26.1

**Comment by czhang03** [comment] 2023-07-22 15:17
It seems like signal updated their backup format: https://github.com/signalapp/Signal-Android/commit/c6473ca9e63236af3eae9959a50cfa643d53272e

import worked fine on older version, but after I updated this morning, it stopped working.

**Comment by andreas1107** [comment] 2023-07-31 09:28
I have the same issue. My solution: I restored an old Signal backup from 2 June 2023 and it worked fine in Molly v6.25.5-1-FOSS.

**Comment by pabloscloud** [comment] 2023-08-27 12:19
> This issue affects account "transfer from android device" as well, but importing backup generated by Signal works, so it seems that backups generated by Molly do contain malformed data.

I can confirm this is true. (v.6.30.4-1-FOSS Molly -> 6.30.4 Signal)

**Comment by valldrac** [comment] 2023-08-27 17:02
> I can confirm this is true. (v.6.30.4-1-FOSS Molly -> 6.30.4 Signal)

Sorry, but I can't replicate the bug. I just tested the same scenario and it's working.

I'd need some debug info about the crash. Also, could you please try importing the backup that failed on Molly?

If you don't want to uninstall your app to run the tests and risk losing your account, you can install our app for testing. Pick the staging version here: https://github.com/mollyim/mollyim-insider-android/releases/tag/v6.30.4-1.rc1

**Comment by pabloscloud** [comment] 2023-09-01 00:11
I did always test inport with Molly too.

I faced the exact same issues as described here and solved the import issue too, while loosing quite a ton of messages:
https://github.com/bepaald/signalbackup-tools/issues/118

I am already back on stock Signal to avoid missing messages in the future.

**Comment by valldrac** [comment] 2023-09-01 07:21
Sorry for the data loss. I'm closing this issue because I also can't reproduce the bug, and I don't want it to become a catch-all for any backup-related problems since those can have multiple root causes.

**Closed by valldrac** 2023-09-01 07:21 UTC
Labels: bug

**Comment by pabloscloud** [comment] 2023-09-02 16:59
Can't really help as I won't share my backup publicly :)

**Comment by dreamflasher** [comment] 2023-09-02 17:05
Well, we provided a lot of info to debug, multiple people continously report that bug, it's a very specific bug and nowhere near a catch-all, and well it's the reason I won't touch Molly again until this is fixed. It's all we can do.

**Comment by secoepdev** [comment] 2023-10-20 14:50
Hi, I have the same issue `"Backup contains malformed data"`  backup was created by Molly version 6.35.3-1 and trying to restore with the same version. Official Signal client gives the same error. Is there any solution to get Molly restored from the backup file?

**Comment by pabloscloud** [comment] 2023-10-21 01:02
> Hi, I have the same issue `"Backup contains malformed data"` backup was created by Molly version 6.35.3-1 and trying to restore with the same version. Official Signal client gives the same error. Is there any solution to get Molly restored from the backup file?

You can use https://github.com/bepaald/signalbackup-tools and try to remove the malformed data. Not everything will be there, but everything that isn't malformed. Good luck 🤞🍀
