### ISSUE TITLE
Can't register to FCM, `Firebase Installations Service is unavailable.`

### ISSUE THREAD

**Issue by haarp** [mollyim/mollyim-android#406] opened 2024-12-05 21:32 UTC
### Is there an existing request for this?

- [X] I have searched the existing issues

### Bug description

(There seems to be a problem with the bug report template, it's not available. Hence why I'm opening this as a "feature request")

Hey!

A few days ago, Molly started using the WebSocket service to receive notifications. It was using FCM just fine before that, and I'm unsure what changed. Explicitely setting it to FCM again in the notification settings doesn't fix it.

```
12-05 22:00:01.328 13065 30911 D TrafficStats: tagSocket(176) with statsTag=0x8003, statsUid=-1
12-05 22:00:01.330  1630  1630 I NotificationService: Cannot find enqueued record for key: 0|im.molly.app|313399|null|10224
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: Failed to get FIS auth token
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.1.0:5)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.1.0:9)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.messaging.GmsRpc.setDefaultAttributesToBundle(GmsRpc.java:260)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.messaging.GmsRpc.startRpc(GmsRpc.java:222)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.messaging.GmsRpc.getToken(GmsRpc.java:180)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.messaging.FirebaseMessaging.lambda$blockingGetToken$10(FirebaseMessaging.java:617)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.messaging.FirebaseMessaging.$r8$lambda$lbvegBVb7mfDC14TEL2O2bE8NL0(FirebaseMessaging.java:0)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda5.start(R8$$SyntheticClass:0)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.messaging.RequestDeduplicator.getOrStartGetTokenRequest(RequestDeduplicator.java:67)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(FirebaseMessaging.java:613)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$4(FirebaseMessaging.java:393)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.messaging.FirebaseMessaging.$r8$lambda$2qw-XzcEnBhCYM_NFRv12nL9Swg(FirebaseMessaging.java:0)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.3.0:2)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at java.lang.Thread.run(Thread.java:1012)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: Caused by: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.generateAuthToken(FirebaseInstallationServiceClient.java:447)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.installations.FirebaseInstallations.fetchAuthTokenFromServer(FirebaseInstallations.java:566)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:389)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$3(FirebaseInstallations.java:372)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.installations.FirebaseInstallations.$r8$lambda$_LVWvNUQ4Iq8r5kiH7vh8J1nAu0(FirebaseInstallations.java:0)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.installations.FirebaseInstallations$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:0)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.concurrent.SequentialExecutor$1.run(SequentialExecutor.java:117)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.concurrent.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:229)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.concurrent.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:174)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.concurrent.CustomThreadFactory.$r8$lambda$XB8AY3Hcio74byWuTzgVEC3Hiek(CustomThreadFactory.java:0)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
12-05 22:00:01.334 13065 13101 E FirebaseMessaging: 	... 1 more
12-05 22:00:01.343 13065 30911 D TrafficStats: tagSocket(176) with statsTag=0x8003, statsUid=-1
12-05 22:00:01.348  4370  4370 D GmsGcmRegister: onBind: Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
12-05 22:00:01.355  4370  4370 D GmsGcmRegister: handleMessage: package=im.molly.app what=1 id=24
12-05 22:00:01.355 13065 30911 D TrafficStats: tagSocket(176) with statsTag=0x8003, statsUid=-1
12-05 22:00:01.374  1630  1630 I NotificationService: Cannot find enqueued record for key: 0|im.molly.app|313399|null|10224
12-05 22:00:01.401  4370 30924 D GmsHttpFormClient: -- Request --
12-05 22:00:01.401  4370 30924 D GmsHttpFormClient: device=<....>&app=im.molly.app&cert=49ce310cdd0c09c8c34eb31a8005c6bf13f5a4f1&app_ver=148901&X-subtype=312334754206&X-app_ver=148901&X-osv=35&X-cliv=fcm-23.1.2&X-gmsv=240913025&X-appid=cmW78RVVReeZylYq4LQOxe&X-scope=*&X-gmp_app_id=1%3A91233741263%3Aandroid%3A0cf3d030865ac67d548aba&X-firebase-app-name-hash=R1dAH9Ui7M-ynoznwBdw01tLxhI&X-app_ver_name=v7.26.1-1&target_ver=34&sender=<....>

```

Molly 7.26.1-1 from Molly's (non-FOSS) F-droid repo
CalyxOS 6.1.0 with microg, Cloud Messaging enabled, connected, and working or other apps

Thanks!

**Comment by haarp** [comment] 2024-12-05 21:34
I've now unregistered Molly from MicroG and it doesn't seem to be re-registering :(

Let's see if clearing data helps

**Comment by valldrac** [comment] 2024-12-09 11:47
Any updates on this? The full log would help too.

**Comment by haarp** [comment] 2024-12-09 14:50
I've reinstalled Molly and re-imprted the backup. After a while it managed to re-register FCM, but the problem persisted. Meanwhile, other apps managed to send FCM notifications just fine.

I've had another look today and it seems the problem mysteriously fixed itself. FCM is working again. I don't understand. Why only this one app? Is there some sort of rate-limit on the server-side maybe?

Thanks for reading tho! Feel free to close at your discretion.

**Comment by valldrac** [comment] 2024-12-09 15:06
Thanks for the update! If it happens again, don't reinstall Molly. Just switch from WebSocket to FCM in the settings to trigger an FCM re-registration. I don’t think the issue is in Molly, so check the microG logs for errors from Google’s backend. Closing for now.

**Closed by valldrac** 2024-12-09 15:06 UTC
Labels: bug, needs-information
