### ISSUE TITLE
Out-of-bounds exception when trying to restore backup from file

### ISSUE THREAD

**Issue by gammerboy** [mollyim/mollyim-android#47] opened 2021-05-16 11:17 UTC
The app crashes / closes  when restoring backup from file.

Steps to reproduce:
1. Install the app.
2. open app and turn on database encryption with a password
3. Try restoring backup from file by selecting the file and entering the numeric code for the backup.
4. The ui shows restoring and then crashes.

app version: 5.8.10-1
android version: 11

Note: Used to work when I had the initial database encryption off.

**Comment by valldrac** [comment] 2021-05-16 14:21
That's weird. It worked in my tests.

I would need the debug log to find the cause. Please read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports, specially the section "How to capture a debug log". Then share the link to the debug log here or email it to support@molly.im

Restart the app, and then in the menu of the passphrase prompt you can get the debug log after the crash.

**Comment by gammerboy** [comment] 2021-05-16 17:24
Logcat output for the time period after opening the app and trying to restore the backup along with the crash.

`05-16 22:01:45.519 19276 19276 V GrantPermissionsActivity: Permission grant result requestId=5904926831172884678 callingUid=10155 callingPackage=im.molly.app permission=android.permission.READ_PHONE_STATE isImplicit=false result=4
05-16 22:01:45.519 19276 19276 V GrantPermissionsActivity: Permission grant result requestId=5904926831172884678 callingUid=10155 callingPackage=im.molly.app permission=android.permission.READ_PHONE_NUMBERS isImplicit=false result=4
05-16 22:01:45.598 19276 21881 D OpenGLRenderer: endAllActiveAnimators on 0x5f2df310d0 (RippleDrawable) with handle 0x5e4def6b30
05-16 22:01:45.637 22740 22740 I WelcomeFragment: No number detected
05-16 22:01:45.648 22740 22740 D LoggingFragment: [TransferOrRestoreFragme] onCreate()
05-16 22:01:45.662  2940  2953 I ndroid.systemu: NativeAlloc concurrent copying GC freed 30836(1554KB) AllocSpace objects, 2(40KB) LOS objects, 49% free, 9490KB/18MB, paused 94us total 118.726ms
05-16 22:01:45.664 22740 22740 D LoggingFragment: [TransferOrRestoreFragme] onStart()
05-16 22:01:45.666 22740 22740 D LoggingFragment: [WelcomeFragment] onStop()
05-16 22:01:46.573 22740 22740 D LoggingFragment: [ChooseBackupFragment] onCreate()
05-16 22:01:46.590 22740 22740 D LoggingFragment: [ChooseBackupFragment] onStart()
05-16 22:01:46.592 22740 22740 D LoggingFragment: [TransferOrRestoreFragme] onStop()
05-16 22:01:48.873  2504 20988 I ActivityTaskManager: START u0 {act=android.intent.action.GET_CONTENT cat=[android.intent.category.OPENABLE] typ=application/octet-stream cmp=com.android.documentsui/.picker.PickActivity (has extras)} from uid 10155
05-16 22:01:48.878   559   559 I android.hardware.power-service-qti: Power setMode: 5 to: 1
05-16 22:01:48.889  2504 20988 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (4469510)
05-16 22:01:48.933 19523 19523 D Documents: shouldRestrictStorageAccessFramework = true, packageName = im.molly.app
05-16 22:01:48.969 19523 19523 E oid.documentsu: No package ID ff found for ID 0xffffffff.
05-16 22:01:48.984 19523 19523 W SelectionTracker: Setting gestureTooltypes is likely to result in unexpected behavior.
05-16 22:01:48.988 19523 19523 E oid.documentsu: No package ID ff found for ID 0xffffffff.
05-16 22:01:49.000 19523 19523 E oid.documentsu: No package ID ff found for ID 0xffffffff.
05-16 22:01:49.010 19523 20797 I ProvidersCache: Provider returned no roots. Possibly naughty: org.nextcloud.beta.documents
05-16 22:01:49.101 19523 19523 E oid.documentsu: No package ID ff found for ID 0xffffffff.
05-16 22:01:49.101  2504  2651 I ActivityTaskManager: Displayed com.android.documentsui/.picker.PickActivity: +221ms
05-16 22:01:49.136 19523 19523 E oid.documentsu: No package ID ff found for ID 0xffffffff.
05-16 22:01:49.166   559   559 I android.hardware.power-service-qti: Power setMode: 5 to: 0
05-16 22:01:49.311 22740 22740 D LoggingFragment: [ChooseBackupFragment] onStop()
05-16 22:01:49.589 22740 22740 I ApplicationContext: App is no longer visible.
05-16 22:01:49.593 22740 23338 D IncomingMessageObserver: Network: true, Foreground: false, FCM: true, Censored: false, Registered: false, Websocket Registered: false, Proxy: false
05-16 22:01:50.290 19523 19523 E oid.documentsu: No package ID ff found for ID 0xffffffff.
05-16 22:01:50.310 19523 19523 E oid.documentsu: No package ID ff found for ID 0xffffffff.
05-16 22:01:50.356 19523 19523 W SelectionTracker: Setting gestureTooltypes is likely to result in unexpected behavior.
05-16 22:01:50.624 19276 19290 W System  : A resource failed to call release.
05-16 22:01:51.323 19523 19523 E oid.documentsu: No package ID ff found for ID 0xffffffff.
05-16 22:01:51.352 19523 19523 E oid.documentsu: No package ID ff found for ID 0xffffffff.
05-16 22:01:51.397 19523 19523 W SelectionTracker: Setting gestureTooltypes is likely to result in unexpected behavior.
05-16 22:01:51.938  2504  3817 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
05-16 22:01:52.127 22740 22740 D LoggingFragment: [RestoreBackupFragment] onCreate()
05-16 22:01:52.144 22740 22740 I RestoreBackupFragment: Backup restore.
05-16 22:01:52.146 22740 22740 I RestoreBackupFragment: Restoring backup from passed uri
05-16 22:01:52.148 22740 22740 D LoggingFragment: [RestoreBackupFragment] onStart()
05-16 22:01:52.151 22740 22740 I ApplicationContext: App is now visible.
05-16 22:01:52.151 22740 22740 D FrameRateTracker: Beginning frame rate tracking. Screen refresh rate: 60.00 hz, or 16.67 ms per frame.
05-16 22:01:52.152 22740 23339 I FeatureFlags: Scheduling remote config refresh.
05-16 22:01:52.155 22740 22740 D ApplicationContext: onStart() took 4 ms
05-16 22:01:52.157 22740 23338 D IncomingMessageObserver: Network: true, Foreground: true, FCM: true, Censored: false, Registered: false, Websocket Registered: false, Proxy: false
05-16 22:01:52.187  3460  3479 W System  : A resource failed to call release.
05-16 22:01:52.188  3460  3479 I chatty  : uid=10142(com.android.launcher3) FinalizerDaemon identical 1 line
05-16 22:01:52.188  3460  3479 W System  : A resource failed to call release.
05-16 22:01:52.196  2940  2953 I ndroid.systemu: NativeAlloc concurrent copying GC freed 3086(208KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 9457KB/18MB, paused 102us total 111.724ms
05-16 22:01:52.197  2940  2955 W System  : A resource failed to call release.
05-16 22:01:52.199 22740 23339 I JobSchedulerScheduler: JobScheduler enqueue of NETWORK (-1733499378)
05-16 22:01:52.231 22740 22778 I BackupUtil: isBackupFileReadable: The document at the specified Uri looks like a readable backup
05-16 22:01:52.232 22740 23339 I Job     : [JOB::137cdeac-bdd9-43bc-ae94-2ed3cb619fda][RemoteConfigRefreshJob] onSubmit() (Time Since Submission: 80 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
05-16 22:01:52.232 22740 23339 I RetrieveProfileJob: Registration not complete. Skipping.
05-16 22:01:52.233 22740 23339 I GroupV1MigrationJob: Registration not complete. Skipping.
05-16 22:01:52.253 22740 23343 I JobRunner: [JOB::137cdeac-bdd9-43bc-ae94-2ed3cb619fda][RemoteConfigRefreshJob][1] Running job. (Time Since Submission: 99 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
05-16 22:01:52.265 22740 23343 W RemoteConfigRefreshJob: Not registered. Skipping.
05-16 22:01:52.267 22740 23343 I JobRunner: [JOB::137cdeac-bdd9-43bc-ae94-2ed3cb619fda][RemoteConfigRefreshJob][1] Job finished with result SUCCESS in 15 ms. (Time Since Submission: 114 ms, Lifespan: 86400000 ms, Run Attempt: 1/Unlimited)
05-16 22:01:52.273 22740 22740 I JobSchedulerScheduler: Waking due to job: -1733499378
05-16 22:01:52.408 22740 22740 D LoggingFragment: [ChooseBackupFragment] onDestroy()
05-16 22:01:52.496 22740 22751 I im.molly.app: Compiler allocated 30MB to compile java.util.List org.thoughtcrime.securesms.jobs.FastJobStorage.getPendingJobsWithNoDependenciesInCreatedOrder(long)
05-16 22:01:54.417   573 15066 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0x7f
05-16 22:01:58.009 22740 22740 I RestoreBackupFragment: Prompt for backup passphrase shown to user.
05-16 22:01:58.692  3677  3677 I LatinIME: Starting input. Cursor position = 0,0
05-16 22:01:58.734  3677  3677 W SubtypeLocaleUtils: KeyboardLayoutSet not found, use QWERTY: locale=en_AU extraValue=TrySuppressingImeSwitcher,AsciiCapable,SupportTouchPositionCorrection,EmojiCapable
05-16 22:02:09.218   441   441 I hwservicemanager: getTransport: Cannot find entry android.hardware.power.stats@1.0::IPowerStats/default in either framework or device manifest.
05-16 22:02:09.230   441   441 I hwservicemanager: getTransport: Cannot find entry android.hardware.power@1.0::IPower/default in either framework or device manifest.
05-16 22:02:09.231  2504  2665 E BatteryStatsService: Unable to load Power Hal or power.stats HAL
05-16 22:02:09.238   441   441 I hwservicemanager: getTransport: Cannot find entry android.hardware.power.stats@1.0::IPowerStats/default in either framework or device manifest.
05-16 22:02:09.240   441   441 I hwservicemanager: getTransport: Cannot find entry android.hardware.power@1.0::IPower/default in either framework or device manifest.
05-16 22:02:09.240  2504  2665 E BatteryStatsService: Unable to load Power Hal or power.stats HAL
05-16 22:01:55.507  2504  3817 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
05-16 22:02:09.265  2504  2665 D KernelCpuUidUserSysTimeReader: Removing uids 99002-99002
05-16 22:02:11.881  3041 15072 D DhcpClient: Received packet: d8:f8:83:35:97:fb OFFER, ip /192.168.20.86, mask /255.255.255.0, DNS servers: /192.168.30.101 , gateways [/192.168.20.1] lease time 86400, domain localdomain
05-16 22:02:12.524  2005  2086 I ThermalEngine: ACTION: GPU - Setting GPU[0] to 652800000
05-16 22:02:18.948  3041 15072 D DhcpClient: Received packet: d8:f8:83:35:97:fb OFFER, ip /192.168.20.86, mask /255.255.255.0, DNS servers: /192.168.30.101 , gateways [/192.168.20.1] lease time 86400, domain localdomain
05-16 22:02:28.570 22740 22841 I RestoreBackupFragment: Starting backup restore.
05-16 22:02:28.584 22740 22769 D OpenGLRenderer: endAllActiveAnimators on 0x5f2dfa0190 (RippleDrawable) with handle 0x5e4df6e200
05-16 22:02:28.585 22740 22841 W KeyStore: KeyStore exception
05-16 22:02:28.585 22740 22841 W KeyStore: android.os.ServiceSpecificException:  (code 7)
05-16 22:02:28.585 22740 22841 W KeyStore:      at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
05-16 22:02:28.585 22740 22841 W KeyStore:      at android.os.Parcel.createException(Parcel.java:2357)
05-16 22:02:28.585 22740 22841 W KeyStore:      at android.os.Parcel.readException(Parcel.java:2340)
05-16 22:02:28.585 22740 22841 W KeyStore:      at android.os.Parcel.readException(Parcel.java:2282)
05-16 22:02:28.585 22740 22841 W KeyStore:      at android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:988)
05-16 22:02:28.585 22740 22841 W KeyStore:      at android.security.KeyStore.get(KeyStore.java:233)
05-16 22:02:28.585 22740 22841 W KeyStore:      at android.security.KeyStore.get(KeyStore.java:222)
05-16 22:02:28.585 22740 22841 W KeyStore:      at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:160)
05-16 22:02:28.585 22740 22841 W KeyStore:      at java.security.KeyStoreSpi.engineEntryInstanceOf(KeyStoreSpi.java:583)
05-16 22:02:28.585 22740 22841 W KeyStore:      at java.security.KeyStore.entryInstanceOf(KeyStore.java:1631)
05-16 22:02:28.585 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.crypto.KeyStoreHelper.hasKeyStoreEntry(KeyStoreHelper.java:147)
05-16 22:02:28.585 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getOrCreateKeyStoreEntry(KeyStoreHelper.java:82)
05-16 22:02:28.585 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.crypto.KeyStoreHelper.seal(KeyStoreHelper.java:51)
05-16 22:02:28.585 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.backup.BackupPassphrase.set(BackupPassphrase.java:47)
05-16 22:02:28.585 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:247)
05-16 22:02:28.585 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:239)
05-16 22:02:28.585 22740 22841 W KeyStore:      at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-16 22:02:28.585 22740 22841 W KeyStore:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-16 22:02:28.585 22740 22841 W KeyStore:      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
05-16 22:02:28.585 22740 22841 W KeyStore:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-16 22:02:28.585 22740 22841 W KeyStore:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-16 22:02:28.585 22740 22841 W KeyStore:      at java.lang.Thread.run(Thread.java:923)
05-16 22:02:28.587 22740 22841 W KeyStore: KeyStore exception
05-16 22:02:28.587 22740 22841 W KeyStore: android.os.ServiceSpecificException:  (code 7)
05-16 22:02:28.587 22740 22841 W KeyStore:      at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
05-16 22:02:28.587 22740 22841 W KeyStore:      at android.os.Parcel.createException(Parcel.java:2357)
05-16 22:02:28.587 22740 22841 W KeyStore:      at android.os.Parcel.readException(Parcel.java:2340)
05-16 22:02:28.587 22740 22841 W KeyStore:      at android.os.Parcel.readException(Parcel.java:2282)
05-16 22:02:28.587 22740 22841 W KeyStore:      at android.security.keystore.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:988)
05-16 22:02:28.587 22740 22841 W KeyStore:      at android.security.KeyStore.get(KeyStore.java:233)
05-16 22:02:28.587 22740 22841 W KeyStore:      at android.security.KeyStore.get(KeyStore.java:222)
05-16 22:02:28.587 22740 22841 W KeyStore:      at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:165)
05-16 22:02:28.587 22740 22841 W KeyStore:      at java.security.KeyStoreSpi.engineEntryInstanceOf(KeyStoreSpi.java:583)
05-16 22:02:28.587 22740 22841 W KeyStore:      at java.security.KeyStore.entryInstanceOf(KeyStore.java:1631)
05-16 22:02:28.587 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.crypto.KeyStoreHelper.hasKeyStoreEntry(KeyStoreHelper.java:147)
05-16 22:02:28.587 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.crypto.KeyStoreHelper.getOrCreateKeyStoreEntry(KeyStoreHelper.java:82)
05-16 22:02:28.587 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.crypto.KeyStoreHelper.seal(KeyStoreHelper.java:51)
05-16 22:02:28.587 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.backup.BackupPassphrase.set(BackupPassphrase.java:47)
05-16 22:02:28.587 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:247)
05-16 22:02:28.587 22740 22841 W KeyStore:      at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:239)
05-16 22:02:28.587 22740 22841 W KeyStore:      at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-16 22:02:28.587 22740 22841 W KeyStore:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-16 22:02:28.587 22740 22841 W KeyStore:      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
05-16 22:02:28.587 22740 22841 W KeyStore:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-16 22:02:28.587 22740 22841 W KeyStore:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-16 22:02:28.587 22740 22841 W KeyStore:      at java.lang.Thread.run(Thread.java:923)
05-16 22:02:28.629   463   463 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
05-16 22:02:28.629   463   463 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
05-16 22:02:29.896 22740 22841 V Cursor  : Filling cursor window with start position:0 required position:0
05-16 22:02:29.925 22740 22841 I FullBackupImporter: Ignoring import for statement: CREATE TABLE sqlite_sequence(name,seq)
05-16 22:02:30.393 22740 22841 W FullBackupImporter: Bad MAC for attachment 1620969530886! Can't restore it.
05-16 22:02:30.393 22740 22841 W FullBackupImporter: org.thoughtcrime.securesms.backup.FullBackupImporter$BadMacException
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readAttachmentTo(FullBackupImporter.java:389)
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at org.thoughtcrime.securesms.backup.FullBackupImporter.processAttachment(FullBackupImporter.java:174)
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:107)
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:79)
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:248)
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:239)
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-16 22:02:30.393 22740 22841 W FullBackupImporter:    at java.lang.Thread.run(Thread.java:923)
05-16 22:02:30.402 22740 22841 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-16 22:02:30.402 22740 22841 E AndroidRuntime: Process: im.molly.app, PID: 22740
05-16 22:02:30.402 22740 22841 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:415)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
05-16 22:02:30.402 22740 22841 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at java.lang.System.arraycopy(System.java:524)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:405)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:345)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:100)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:79)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:248)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:239)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-16 22:02:30.402 22740 22841 E AndroidRuntime:        ... 4 more
05-16 22:02:30.403 22740 22841 E SignalUncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at android.os.AsyncTask$4.done(AsyncTask.java:415)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at java.lang.Thread.run(Thread.java:923)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException: Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=0 srcPos=-10 dst.length=10 dstPos=0 length=10
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at java.lang.System.arraycopy(System.java:524)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:405)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.FullBackupImporter$BackupRecordInputStream.readFrame(FullBackupImporter.java:345)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:100)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:79)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:248)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:239)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at android.os.AsyncTask$3.call(AsyncTask.java:394)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-16 22:02:30.403 22740 22841 E SignalUncaughtException:       ... 4 more
05-16 22:02:30.430 22740 22841 I JobManager: Successfully flushed.
05-16 22:02:30.433  2504 23466 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
05-16 22:02:30.434  2504 22724 W ActivityTaskManager:   Force finishing activity im.molly.app/org.thoughtcrime.securesms.registration.RegistrationNavigationActivity
05-16 22:02:30.475 22740 22841 I Process : Sending signal. PID: 22740 SIG: 9
05-16 22:02:30.486   439   439 E lowmemorykiller: Error writing /proc/22740/oom_score_adj; errno=22
05-16 22:02:30.495  2504 20988 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10142?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
05-16 22:02:30.591  2504 20712 I WindowManager: WIN DEATH: Window{ca50bdc u0 im.molly.app/org.thoughtcrime.securesms.registration.RegistrationNavigationActivity}
05-16 22:02:30.591  2504  3866 I ActivityManager: Process im.molly.app (pid 22740) has died: fg +50 FGS
05-16 22:02:30.608  2940  2953 I ndroid.systemu: NativeAlloc concurrent copying GC freed 8369(492KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 9501KB/18MB, paused 121us total 143.233ms
05-16 22:02:30.614  2504  2609 W ActivityManager: setHasOverlayUi called on unknown pid: 22740
05-16 22:02:30.637  2009  2009 I Zygote  : Process 22740 exited due to signal 9 (Killed)
05-16 22:02:30.676  2504  2655 I libprocessgroup: Successfully killed process cgroup uid 10155 pid 22740 in 84ms
05-16 22:02:33.650  2504  3817 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
05-16 22:02:34.640  2005  2088 I ThermalEngine: Monitor : quiet_therm = 42, msm_therm = 42, ufs_therm = 42, battery_therm = 370,current_now = 1274000
05-16 22:02:38.209 19598 20225 V ArbitraryDataProvider: Updating arbitrary data with cloud id: global key: media_folders value: {"imageMediaFolders":[],"videoMediaFolders":[]}
`

**Comment by gammerboy** [comment] 2021-05-16 17:30
Is there a better way to upload / attach logs. Please do advice.

**Comment by gammerboy** [comment] 2021-05-16 18:18
So the backup file I am having issue with is the one I took before resetting the phone. I did wait and checked that the backup was done before taking the file and resetting the phone. This is the file which crashes the app when I try to restore it.

After resetting I opened the app without backup and then made a backup and cleared data and tried restoring the backup with the database encryption and this works without crashing. So I am not sure why the file from before the reset causes the crash.

**Comment by valldrac** [comment] 2021-05-16 22:28
Thanks for the log. It seems the backup file is damaged.

Now I realize it could the app was locked in the middle of a backup operation in background. And thus the backup file is truncated.

This is a bug indeed. I'll fix it.

**Comment by gammerboy** [comment] 2021-05-17 07:06
Okay. :) 
Do I close the issue now?

**Comment by valldrac** [comment] 2021-05-17 08:36
Leave it open. I'll close it when I commit the fix.

**Comment by gammerboy** [comment] 2021-05-17 09:28
Okay. Got it.
Thank you.

**Comment by valldrac** [comment] 2021-05-19 20:59
I verified that the backups are not affected by Molly's locking system. Basically the backup is written to a temporary file until it completes and then it's renamed to the final backup file. Renaming files is an atomic operation, so there is no bug to fix.

I'm going to close this issue because we cannot know why your backup file is corrupted. If there was an error, it would be logged in your old phone.

**Comment by gammerboy** [comment] 2021-06-15 07:53
@valldrac Just an update on the backup restore situation and apologies for not grabbing logs. it seems like the issue might be reproducible when you click to backup and once the first backup is made to click to create another backup in lets say within 5 minutes I guess. I did wait to see it show the "last backup: Now" both the times but trying to restore the second backup.

**Comment by valldrac** [comment] 2021-06-15 09:08
Backup jobs cannot run concurrently, but only one at a time. I think we're just increasing the probabilities of reproducing the issue.

I search in the Signal issues and found exactly the crash you reported first (debuglog above): https://github.com/signalapp/Signal-Android/issues/11076

Sorry for not realizing that in the first place. My first though was it must be an issue in Molly's locking. Please report your issue to Signal and let's see if they can fix it. I would try to help to, but no guarantees. Note they mentioned a tool that could help you to repair the backups.

**Comment by gammerboy** [comment] 2021-06-15 10:26
haha I didn't think about checking signals issues before reporting here. I guess should try checking for the same issue on a phone running stock rom with signal if it can be triggered by making backups concurrently in a few mins and then report the issue on signal's issues if it happens there too. 

> Note they mentioned a tool that could help you to repair the backups.

It's not really a big deal to not be able to restore backups for me for now so maybe can just look into it to play around but thank you for looking into the issue might be helpful for me later or for anyone who might come up with the issue.

> My first though was it must be an issue in Molly's locking
I think it must be cause of the way I framed the issue and the title too.

**Comment by dM7se** [comment] 2022-12-27 23:53
Hi,
is there any solution for the issue?
I recieve the error: Cannot restore Backup from an newer version of Signal.
When I try to restore from local backup.
When I try to transfer (wireless) I recieve also an error.

Device:
Samsung Galaxy S21 Ultra 5G
Android 13
Molly: 6.3.6-1
Signal: 6.6.3

**Comment by valldrac** [comment] 2022-12-28 20:22
> I recieve the error: Cannot restore Backup from an newer version of Signal.

You have to wait for Molly to catch up with latest Signal release. As described in the README: "To import from Signal use a matching or newer version of Molly."

Right now Molly is some versions behind: 6.3.6 < 6.6.3.

This is unrelated to the original issue report.

**Comment by dM7se** [comment] 2022-12-29 13:38
Thanks you for the Info.
I hoped that there is another solution to switch to Molly instead to wait.

**Closed** 2024-01-24 19:46 UTC
Labels: bug, upstream
