### ISSUE TITLE
molly (noFOSS-version) not register in microg

### ISSUE THREAD

**Issue by morty303** [mollyim/mollyim-android#292] opened 2024-03-02 04:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

hello,
if i install the nonFOSS-version from fdroid and want to register then there comes a popup from microg to allow it for pushservice.
after allowing its not listed under registered apps.
if i use newest version of microg then molly isn't detected at beginning of installation.
all molly noFOSS-versions can't be registered in microg.
the original signal apk works perfect with microg.
can you fix it in comming updates to get it work with microg?

### Steps to reproduce

1.
2.

### Molly version

7.0.1-1 and older releases

### Android version

Android 13

**Comment by valldrac** [comment] 2024-03-05 04:08
Closing this as a duplicate of #291

**Closed by valldrac** 2024-03-05 04:08 UTC
